spring:
  application:
    name: macro-site-route

server:
  port: 8200

# websocket参数

#dubbo:
#  application:
#    name: dubbo-chat-server
#  registry:
#    address: zookeeper://47.93.42.142:2181

management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true

# 自定义配置
app:
  zk:
    addr: 47.93.42.142:2181
    connect:
      timeout: 15000
    root: /route
  ws:
    server:
      port: 10000
    heartbeat:
      time: 30
  route:
#    url: http://localhost:8100/
    url: http://10.128.207.76:8100/