// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatMsg.proto

package com.xuke.macrosite.common.protobuf;

public final class ChatMsgProto {
  private ChatMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.ChatMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 type = 1;</code>
     * @return The type.
     */
    int getType();

    /**
     * <code>int32 uid = 2;</code>
     * @return The uid.
     */
    int getUid();

    /**
     * <code>.protocol.ChatContent content = 3;</code>
     * @return Whether the content field is set.
     */
    boolean hasContent();
    /**
     * <code>.protocol.ChatContent content = 3;</code>
     * @return The content.
     */
    com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContent getContent();
    /**
     * <code>.protocol.ChatContent content = 3;</code>
     */
    com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContentOrBuilder getContentOrBuilder();

    /**
     * <code>string send_time = 4;</code>
     * @return The sendTime.
     */
    java.lang.String getSendTime();
    /**
     * <code>string send_time = 4;</code>
     * @return The bytes for sendTime.
     */
    com.google.protobuf.ByteString
        getSendTimeBytes();
  }
  /**
   * <pre>
   * 返回实体
   * </pre>
   *
   * Protobuf type {@code protocol.ChatMsg}
   */
  public static final class ChatMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.ChatMsg)
      ChatMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatMsg.newBuilder() to construct.
    private ChatMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatMsg() {
      sendTime_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              type_ = input.readInt32();
              break;
            }
            case 16: {

              uid_ = input.readInt32();
              break;
            }
            case 26: {
              com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContent.Builder subBuilder = null;
              if (content_ != null) {
                subBuilder = content_.toBuilder();
              }
              content_ = input.readMessage(com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContent.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(content_);
                content_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              sendTime_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_protocol_ChatMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_protocol_ChatMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg.class, com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>int32 type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    public static final int UID_FIELD_NUMBER = 2;
    private int uid_;
    /**
     * <code>int32 uid = 2;</code>
     * @return The uid.
     */
    @java.lang.Override
    public int getUid() {
      return uid_;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContent content_;
    /**
     * <code>.protocol.ChatContent content = 3;</code>
     * @return Whether the content field is set.
     */
    @java.lang.Override
    public boolean hasContent() {
      return content_ != null;
    }
    /**
     * <code>.protocol.ChatContent content = 3;</code>
     * @return The content.
     */
    @java.lang.Override
    public com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContent getContent() {
      return content_ == null ? com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContent.getDefaultInstance() : content_;
    }
    /**
     * <code>.protocol.ChatContent content = 3;</code>
     */
    @java.lang.Override
    public com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContentOrBuilder getContentOrBuilder() {
      return getContent();
    }

    public static final int SEND_TIME_FIELD_NUMBER = 4;
    private volatile java.lang.Object sendTime_;
    /**
     * <code>string send_time = 4;</code>
     * @return The sendTime.
     */
    @java.lang.Override
    public java.lang.String getSendTime() {
      java.lang.Object ref = sendTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sendTime_ = s;
        return s;
      }
    }
    /**
     * <code>string send_time = 4;</code>
     * @return The bytes for sendTime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSendTimeBytes() {
      java.lang.Object ref = sendTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sendTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeInt32(1, type_);
      }
      if (uid_ != 0) {
        output.writeInt32(2, uid_);
      }
      if (content_ != null) {
        output.writeMessage(3, getContent());
      }
      if (!getSendTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sendTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (uid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, uid_);
      }
      if (content_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getContent());
      }
      if (!getSendTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sendTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg)) {
        return super.equals(obj);
      }
      com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg other = (com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg) obj;

      if (getType()
          != other.getType()) return false;
      if (getUid()
          != other.getUid()) return false;
      if (hasContent() != other.hasContent()) return false;
      if (hasContent()) {
        if (!getContent()
            .equals(other.getContent())) return false;
      }
      if (!getSendTime()
          .equals(other.getSendTime())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid();
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      hash = (37 * hash) + SEND_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getSendTime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 返回实体
     * </pre>
     *
     * Protobuf type {@code protocol.ChatMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.ChatMsg)
        com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_protocol_ChatMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_protocol_ChatMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg.class, com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg.Builder.class);
      }

      // Construct using com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        uid_ = 0;

        if (contentBuilder_ == null) {
          content_ = null;
        } else {
          content_ = null;
          contentBuilder_ = null;
        }
        sendTime_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_protocol_ChatMsg_descriptor;
      }

      @java.lang.Override
      public com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @java.lang.Override
      public com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg build() {
        com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg buildPartial() {
        com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg result = new com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg(this);
        result.type_ = type_;
        result.uid_ = uid_;
        if (contentBuilder_ == null) {
          result.content_ = content_;
        } else {
          result.content_ = contentBuilder_.build();
        }
        result.sendTime_ = sendTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg) {
          return mergeFrom((com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg other) {
        if (other == getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getUid() != 0) {
          setUid(other.getUid());
        }
        if (other.hasContent()) {
          mergeContent(other.getContent());
        }
        if (!other.getSendTime().isEmpty()) {
          sendTime_ = other.sendTime_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int uid_ ;
      /**
       * <code>int32 uid = 2;</code>
       * @return The uid.
       */
      @java.lang.Override
      public int getUid() {
        return uid_;
      }
      /**
       * <code>int32 uid = 2;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(int value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 uid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        
        uid_ = 0;
        onChanged();
        return this;
      }

      private com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContent content_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContent, com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContent.Builder, com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContentOrBuilder> contentBuilder_;
      /**
       * <code>.protocol.ChatContent content = 3;</code>
       * @return Whether the content field is set.
       */
      public boolean hasContent() {
        return contentBuilder_ != null || content_ != null;
      }
      /**
       * <code>.protocol.ChatContent content = 3;</code>
       * @return The content.
       */
      public com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContent getContent() {
        if (contentBuilder_ == null) {
          return content_ == null ? com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContent.getDefaultInstance() : content_;
        } else {
          return contentBuilder_.getMessage();
        }
      }
      /**
       * <code>.protocol.ChatContent content = 3;</code>
       */
      public Builder setContent(com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContent value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          contentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.protocol.ChatContent content = 3;</code>
       */
      public Builder setContent(
          com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContent.Builder builderForValue) {
        if (contentBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          contentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.protocol.ChatContent content = 3;</code>
       */
      public Builder mergeContent(com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContent value) {
        if (contentBuilder_ == null) {
          if (content_ != null) {
            content_ =
              com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContent.newBuilder(content_).mergeFrom(value).buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          contentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.protocol.ChatContent content = 3;</code>
       */
      public Builder clearContent() {
        if (contentBuilder_ == null) {
          content_ = null;
          onChanged();
        } else {
          content_ = null;
          contentBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.protocol.ChatContent content = 3;</code>
       */
      public com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContent.Builder getContentBuilder() {
        
        onChanged();
        return getContentFieldBuilder().getBuilder();
      }
      /**
       * <code>.protocol.ChatContent content = 3;</code>
       */
      public com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContentOrBuilder getContentOrBuilder() {
        if (contentBuilder_ != null) {
          return contentBuilder_.getMessageOrBuilder();
        } else {
          return content_ == null ?
              com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContent.getDefaultInstance() : content_;
        }
      }
      /**
       * <code>.protocol.ChatContent content = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContent, com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContent.Builder, com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContentOrBuilder> 
          getContentFieldBuilder() {
        if (contentBuilder_ == null) {
          contentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContent, com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContent.Builder, com.xuke.macrosite.common.protobuf.ChatContentProto.ChatContentOrBuilder>(
                  getContent(),
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        return contentBuilder_;
      }

      private java.lang.Object sendTime_ = "";
      /**
       * <code>string send_time = 4;</code>
       * @return The sendTime.
       */
      public java.lang.String getSendTime() {
        java.lang.Object ref = sendTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sendTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string send_time = 4;</code>
       * @return The bytes for sendTime.
       */
      public com.google.protobuf.ByteString
          getSendTimeBytes() {
        java.lang.Object ref = sendTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sendTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string send_time = 4;</code>
       * @param value The sendTime to set.
       * @return This builder for chaining.
       */
      public Builder setSendTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sendTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string send_time = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendTime() {
        
        sendTime_ = getDefaultInstance().getSendTime();
        onChanged();
        return this;
      }
      /**
       * <code>string send_time = 4;</code>
       * @param value The bytes for sendTime to set.
       * @return This builder for chaining.
       */
      public Builder setSendTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sendTime_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.ChatMsg)
    }

    // @@protoc_insertion_point(class_scope:protocol.ChatMsg)
    private static final com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg();
    }

    public static com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatMsg>
        PARSER = new com.google.protobuf.AbstractParser<ChatMsg>() {
      @java.lang.Override
      public ChatMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xuke.macrosite.common.protobuf.ChatMsgProto.ChatMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ChatMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_ChatMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rChatMsg.proto\022\010protocol\032\021ChatContent.p" +
      "roto\"_\n\007ChatMsg\022\014\n\004type\030\001 \001(\005\022\013\n\003uid\030\002 \001" +
      "(\005\022&\n\007content\030\003 \001(\0132\025.protocol.ChatConte" +
      "nt\022\021\n\tsend_time\030\004 \001(\tB4\n\"com.xuke.macros" +
      "ite.common.protobufB\014ChatMsgProtoH\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xuke.macrosite.common.protobuf.ChatContentProto.getDescriptor(),
        });
    internal_static_protocol_ChatMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_ChatMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_ChatMsg_descriptor,
        new java.lang.String[] { "Type", "Uid", "Content", "SendTime", });
    com.xuke.macrosite.common.protobuf.ChatContentProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
