spring:
  datasource:
    url: jdbc:mysql://47.93.42.142:3306/macro_site?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: xuke
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 47.93.42.142
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 2
    # 连接超时时间（毫秒）
    timeout: 1000

  data:
    mongodb:
      host: 10.128.207.76
      port: 27020
      database: macro_site
#      uri:
  #      password: 123456
#      username: xuke

  #mail
  mail:
    username: 1020194752@qq.com
    password: dxxqmunxaxxbbeha
    host: smtp.qq.com

logging:
  level:
    root: info
    com.xuke.macrosite: debug

# 以下为自定义参数
# jwt参数
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: macro-site-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

# redis参数
redis:
  database: site
  key:
    prefix:
      authCode: "authCode:"
    expire:
      authCode: 120 # 验证码超期时间


# 自定义控制swagger
swagger:
  #是否开启接口文档
  swagger-ui-open: true

# websocket参数
ws:
  port: 8081
